/*
  La liste des conseils. Le site en affiche un différent chaque jour.
  Tu peux en ajouter autant que tu veux : il suffit d'ajouter une ligne entre guillemets.
*/

const CONSEILS = [
	"Prépare tes affaires de sport la veille. Moins tu as de choses à décider, moins tu as d'excuses.",
	"Pas envie ? Mets juste ta tenue de sport. C'est tout. Le plus dur, c'est de commencer.",
	"La règle des 5 minutes : dis-toi que tu fais seulement 5 minutes. 9 fois sur 10, tu continueras.",
	"Une séance moyenne vaut mieux qu'une séance parfaite que tu ne fais pas.",
	"Ne rate jamais deux fois de suite. Rater une séance, c'est normal. En rater deux, c'est le début d'une mauvaise habitude.",
	"Fais ta séance toujours au même moment de la journée. Ton cerveau finira par le faire en automatique.",
	"Prépare une playlist spéciale sport, et écoute-la UNIQUEMENT pendant tes séances. Tu auras hâte de l'entendre.",
	"Bois un grand verre d'eau en te levant. Ton corps a passé la nuit sans boire.",
	"Dors au moins 8 heures. C'est pendant le sommeil que tes muscles se réparent et grossissent.",
	"Tu progresses même quand tu ne le vois pas. Les résultats visibles arrivent souvent après 4 à 6 semaines.",
	"Compare-toi à toi d'il y a un mois, jamais aux autres.",
	"Mange des protéines à chaque repas : œufs, viande, poisson, lentilles, pois chiches, fromage blanc...",
	"La qualité avant la quantité : 8 pompes bien faites valent mieux que 15 pompes bâclées.",
	"Respire ! Souffle pendant l'effort (quand tu pousses), inspire quand tu reviens.",
	"Des courbatures ? C'est normal au début. Bouge doucement, ça passe plus vite qu'en restant immobile.",
	"Une vraie douleur (articulation, douleur vive) n'est pas une courbature : arrête-toi et repose-toi.",
	"Dis à un ami que tu as commencé un programme. Quand quelqu'un sait, on a plus de mal à abandonner.",
	"Encore mieux : trouve quelqu'un qui fait le programme avec toi.",
	"Coche tes exercices au fur et à mesure. Voir les cases se remplir, ça motive.",
	"Ta série 🔥 est précieuse. Ne la laisse pas retomber à zéro pour une journée de flemme.",
	"Mets ton téléphone en mode avion pendant la séance. 30 minutes rien que pour toi.",
	"Le break dance demande de la force dans les épaules, les poignets et le gainage. Chaque séance te rapproche de meilleurs freezes.",
	"Échauffe bien tes poignets avant chaque séance : ils travaillent énormément en break.",
	"La motivation ne dure pas. C'est l'habitude qui te fera continuer. Et une habitude se construit en répétant.",
	"Fatigué ? Fais la version facile des exercices. L'important, c'est de ne pas casser la routine.",
	"Pense à pourquoi tu as commencé. Écris-le sur un papier et colle-le quelque part où tu le vois.",
	"Récompense-toi après une semaine complète : un bon film, un repas que tu aimes, une sortie...",
	"Mange des fruits et des légumes à chaque repas. Ton corps a besoin de vitamines pour récupérer.",
	"Limite les sodas et les boissons sucrées. L'eau, c'est gratuit et c'est ce qu'il y a de mieux.",
	"Prends une photo de toi au début du programme. Tu seras content de comparer dans 8 semaines.",
	"Note combien de pompes tu fais d'affilée aujourd'hui. Refais le test dans un mois : tu seras surpris.",
	"Tu n'as pas besoin d'avoir envie pour commencer. L'envie arrive souvent pendant l'effort.",
	"Si tu n'as vraiment pas le temps, fais un seul tour du circuit. C'est toujours mieux que zéro.",
	"Évite de faire ta séance juste après un gros repas. Attends au moins 1h30.",
	"Un petit en-cas 1h avant la séance (une banane, une tartine) peut te donner de l'énergie.",
	"Le repos fait partie de l'entraînement. Ne culpabilise pas les jours de repos, ils sont prévus !",
	"Chaque séance terminée est un vote pour la personne que tu veux devenir.",
	"Tu as déjà fait le plus dur : commencer. Maintenant, il faut juste continuer.",
	"Regarde une vidéo de breakdancers pour te motiver avant ta séance. Eux aussi ont commencé de zéro.",
	"Fais des étirements avant de dormir : ça aide à la souplesse et à bien dormir.",
	"Ne cherche pas la perfection. Cherche la régularité.",
	"Quand un exercice devient facile, c'est que tu as progressé. Bravo !",
	"Les jours où c'est dur sont ceux qui comptent le plus. N'importe qui s'entraîne quand il est motivé.",
	"Garde une bouteille d'eau à côté de toi pendant la séance.",
	"Tu as le droit de mettre de la musique à fond et de danser entre deux exercices.",
	"Dans 8 semaines, tu seras content d'avoir commencé aujourd'hui."
];
